### ISSUE TITLE
Review cards

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#1]
- [x] fix typos if needed

- [x] make sure all details are correct

- [x] change design so that repeating cards have `underline` and star `(*)` and one time events have regular text

**Comment by leemordechai** [comment]
list of changes:
Saddam Hussein: add to the tutorial ", then select the Saudi player to resolve the event."
South Lebanon Conflict: add "Then, pass the card to the Israeli player to resolve the event."
Change all 'Gain influence' to 'Place influence'
Khomeini attacks Wahhabis: check for double spacing
Shia Uprising: change to 'Shi'a Uprising'
Camp David Peace: get a higher resolution image
The Satanic Verses: change "author..." to ", a British Indian novelist,"

**Comment by leemordechai** [comment]
made all changes; ready to print
