### ISSUE TITLE
Materials

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#10]
- [x] list all needed materials (including amounts)

- [x] buy all needed materials (for game, shipment, and folder)

- [ ] pack all the materials in boxes for shipment

**Comment by leemordechai** [comment]
- small silicon cups(?) or boxes to hold the influence markers

**Comment by veredrec** [comment]
List of materials to buy/have: 

- tokens for influence (?)
- small cups or boxes to hold influence markers
- small bags for all small components (1 for each influence colors, 1 for general components, 1 for event cards, 1 for special cards, 1 for dice = 7 in total per game)
- folder for the marketing materials
- box or envelope for shipping everything together
- maybe an envelop for all the sheets of papres
- board base
- turn marker
