### ISSUE TITLE
Decide about font for title and back of card

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#13]
Decide and design the back of the card, including a decision about the font

**Comment by leemordechai** [comment]
the best one I found is the one for the UAE embassy in the first image here: http://luc.devroye.org/a-sim.html but it's private.
I found the second one here but it isn't so good I think: https://www.dafont.com/theme.php?cat=202&text=Hegemony

**Comment by leemordechai** [comment]
also should consider whether we'd like the Decade cards to have a different back side so they will be easier to distinguish from the regular Event cards
