### ISSUE TITLE
Write to companies

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#2]
Contact the 3 companies to send the prototype or schedule an online meeting

**Comment by leemordechai** [comment]
sent you an email, waiting for you to comment

**Comment by veredrec** [comment]
The emails look great! We should work on the cover sheet and I'll read the posts later, but if you want, you can go ahead and send those.

**Comment by leemordechai** [comment]
sent two emails, waiting for the cover sheet before we can send the third

**Comment by leemordechai** [comment]
called the third company, the information in their blog posts is still accurate but they also offered that we send the email directly to their office
