### ISSUE TITLE
Standardize testing

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#23]
Document the testing process so far, including dates, times, demographic details, etc.

**Comment by leemordechai** [comment]
also whether players played for the first time or not, and what was the final score

**Comment by leemordechai** [comment]
- [x] Google Forms for all testing - V
- [x] input all previous information to Google Forms - L/V, depending on who wrote each form
- [x] design brief response form (up to 5 questions) to playtesters - V
- [x] revise both forms - V

**Comment by veredrec** [comment]
The google form is ready for review/feedback under forms in our new gmail account.
