### ISSUE TITLE
Potential events in the near future

### ISSUE THREAD

**Issue by leemordechai** [veredrec/side-project#24]
Protospiel Chicago (2 hours) - Friday-Sat., 21-23 Sept., $40/person for the entire time or $20-30/person for one day: https://tabletop.events/conventions/protospiel-chicago-2018
Protospiel Wisconsin (6 hours) - Sat. 25 August, $20/person for the day or $35 for the entire Con (not protospiel, two extra days): https://tabletop.events/conventions/coulee-con-2018/pages/protospiel

**Comment by veredrec** [comment]
**GrandCon**: Grand Rapids (2 hours), Sep 14-16, $40/person all weekend, $25/person for Saturday: https://tabletop.events/conventions/grandcon-gaming-convention
**FlatCon**: Bloomington, Illinois (3:15 hours), Oct 12-14, $25/person all weekend, $15/person for Saturday: https://tabletop.events/conventions/flatcon-2018

**Comment by veredrec** [comment]
Every Saturday there is a game night in Elkhart. People there might be interested in play testing the game.

**Comment by leemordechai** [comment]
decided not to go to Grand Rapids
