### ISSUE TITLE
Hidden Objectives - outline

### ISSUE THREAD

**Issue by leemordechai** [veredrec/side-project#29]
5 hidden objectives per regional power; 3 VP (or more)
players can choose their hidden objectives (with a hint for starting players)

- we might have separate hidden objectives for each decade

**Comment by leemordechai** [comment]
I'm thinking a good idea here would be to call this mechanic _Ideology_ or _Agenda_. So for Israel you'd have a few of the following or similar, to keep with the game's theme:
Greater Israel / A Villa in the Jungle / Messianic / Peace Camp / Special US Relationship
Then we can design a complementary mechanic on a few cards that would allow other players to look at these cards (the equivalent of spying/knowing the other player's country well)

**Comment by veredrec** [comment]
Ready for review. I will explain the details when we talk later.

**Comment by leemordechai** [comment]
Develop idea further (+different leaders)
Sketch cards

**Comment by leemordechai** [comment]
continued in #39
