### ISSUE TITLE
To do list - from Sat Aug 25

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#37]
- [x] revise ideology cards - V
- [x] cards - decide about "doubles" - V, L
- [x] cards - improve some cards and add blurbs to some - V
- [x] cards - develop idea and add "interest" mechanic for second decade - V
- [x] materials - save latest version of each file in the new drive - L
- [ ] mechanics - test remove influence with different options - V, L
- [ ] change VP and Player Card according to new color guidelines - V
- [x] fixes in map - L
- [x] save the workflow file in new drive and relevant issue - V
- [x] listen to relevant part in game design podcast (on Sun, Aug 26) - V, L

**Comment by leemordechai** [comment]
continued in #39
