### ISSUE TITLE
Randomize end of phase cards

### ISSUE THREAD

**Issue by veredrec** [veredrec/side-project#7]
Prepare several alternatives for the end of the phase card

**Comment by leemordechai** [comment]
- end of phase/decade cards should have a black border and no symbols. Maybe also a different backside. Graphics and blurb should be the same. 

Soviet Union Dissolves will have 5 versions, in all of which USSR changes to Russia. 1 of these will be drawn randomly once the Phase resolves:
1. die roll; players can lose or gain 2 favor with USSR; player with most US favor will get 4 VP (2 VP if tied)
2. all USSR influence is halved. Player with least US favor loses 1 VP (1 VP if tied)
3. all players lose 2 favor with USSR; player with most US favor can place 2 influence in their home region
4. die roll: each player rolls a die 1-3: lose 2 favor, 4-6: gain 2 favor. Player with most US favor gains 2 VP (1 if tied). 
5. current version

**Comment by leemordechai** [comment]
done, printed draft version
